- name: play level variables
  hosts: local
  connction: local
  vars:
    COURSE: "DevOps wih AWS"
    DURATION: "140HRS"
    TRAINER: "Sivakumar Reddy"
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Course is: {{ COURSE }}, Trainer is: {{ TRAINER }}"